### ISSUE TITLE
Support package names shorter than 3 characters

### ISSUE THREAD

**Issue by rebornplusplus** [canonical/chisel#119]
Chisel does not currently support package names shorter than 3 characters. This is controlled by a few regular expressions specified in the setup package.

https://github.com/canonical/chisel/blob/11a324ceca40c373ae5298ff6b93986340a945d7/internal/setup/setup.go#L245-L247

However, this means that packages like [jq](https://packages.ubuntu.com/noble/jq) are not currently supported. Per the [debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source), the minimum length of a package's name can be 2. 

> Package names (both source and binary, see [Package](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-package)) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least two characters long and must start with an alphanumeric character.

Related: https://github.com/canonical/chisel-releases/pull/116

**Comment by cjdcordeiro** [comment]
unless you see an obvious rationale for keeping that limitation, I'd propose simply putting a PR up for adjusting that limit (unless it's not straightforward)

**Comment by rebornplusplus** [comment]
Yeah, this should be a very easy fix. I will add a PR for it shortly. I wanted to add the "Good first issue" label to this issue in case anyone wanted to try it out, but I can't. :confused:
