### ISSUE TITLE
Checksums for release assets?

### ISSUE THREAD

**Issue by norrisjeremy** [canonical/chisel#122]
Do you have checksums for the assets available at https://github.com/canonical/chisel/releases that can be published?

**Comment by cjdcordeiro** [comment]
Hi @norrisjeremy 

Not yet. But I'll keep this issue open such that we can take the request as a future item for our roadmap.

**Comment by norrisjeremy** [comment]
Hi @cjdcordeiro,

Ok, thanks! It would be great to have the checksums published so that we could verify what is downloaded in our CI pipelines.

Thanks!
Jeremy
