### ISSUE TITLE
security: Upgrade golang.org/x/crypto to remediate CVEs

### ISSUE THREAD

**Issue by bpanesar** [canonical/chisel#126]
Chisel is being reported as containing High Risk Vulnerabilities do to the version of golang.org/x/crypto used in release v0.9.0.

<img width="633" alt="image" src="https://github.com/canonical/chisel/assets/58818842/c20a802b-c15d-4f6e-a968-4c8bdd44186d">

golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
Chisel v0.9.0

Can this please be updated and published as a new release of Chisel?

**Comment by rebornplusplus** [comment]
Raised #130. Thanks for reporting!
