### ISSUE TITLE
AGPL license alternative

### ISSUE THREAD

**Issue by IvanDrag0** [canonical/chisel#137]
Is there a reason Chisel is using the AGPL license instead of the GPLv3/MIT/Apache type licenses that the [other Ubuntu packages](https://ubuntu.com/legal/open-source-licences) are distributed under? Especially since Chisel is not a web-based software.

The reason I'm asking is because my company is looking into adopting Chisel into our processes, however, due to it being distributed under the AGPL license, we cannot use it. Since most companies (even [Google](https://opensource.google/documentation/reference/using/agpl-policy)) ban the use of AGPL, it would make it very difficult for Chisel to be used in a corporate environment.

Is there a version of Chisel that is distributed under one of the other FOSS licenses (e.g. GPLv3, Apache, MIT, etc.)?

**Comment by cjdcordeiro** [comment]
Hi @IvanDrag0 

thank you for seeking clarification on this matter.

We do have and promote the use of the AGPL license for many of our projects (e.g. Juju). Our goal is to promote transparency across the board, including for downstream projects.

Please note that Chisel's output is a minimal Ubuntu filesystem, composed of portions of Ubuntu packages, each with its own copyright data included in the final chiselled filesystem. Chisel itself is not included in the resulting chiselled filesystem.

We do not have any other flavours of Chisel nor do we have immediate plans to change this license.
I can appreciate that some cases are more complex than others. If you're in doubt, I suggest reaching out to your licensing experts, and if needed, to [Canonical's support](https://canonical.com/contact-us) experts.
