### ISSUE TITLE
context deadline exceeded error when running chisel cut

### ISSUE THREAD

**Issue by mthalman** [canonical/chisel#14]
I've been seeing this error several times while building a Dockerfile which is running "chisel cut":

```
#13 [build 3/8] RUN mkdir /rootfs     && chisel cut --release "ubuntu-22.04" --root /rootfs         libicu70_libs
#13 sha256:1921268898730a52b3ffb9270b7fabb790a0c0182faae5fea318c7b6ed1208a9
#13 0.668 2022/07/21 16:28:54 Consulting release repository...
#13 1.138 2022/07/21 16:28:54 Fetching current ubuntu-22.04 release...
#13 1.140 2022/07/21 16:28:54 Processing ubuntu-22.04 release...
#13 1.153 2022/07/21 16:28:54 Selecting slices...
#13 1.153 2022/07/21 16:28:54 Fetching ubuntu 22.04 archive details...
#13 2.195 2022/07/21 16:28:55 Release date: Thu, 21 Apr 2022 17:16:08 UTC
#13 2.196 2022/07/21 16:28:55 Fetching ubuntu 22.04 main component...
#13 5.874 2022/07/21 16:28:59 Fetching ubuntu 22.04 universe component...
#13 35.89 error: cannot fetch from archive: context deadline exceeded (Client.Timeout or context cancellation while reading body)
#13 ERROR: executor failed running [/bin/sh -c mkdir /rootfs     && chisel cut --release "ubuntu-22.04" --root /rootfs         libicu70_libs]: exit code: 1
```

Simply re-running the build will cause it to succeed typically.

**Comment by mthalman** [comment]
cc @woky

**Comment by woky** [comment]
@mthalman That's error from Go's `http.Client` about timeout when reading response. I admit that the error message is a bit confusing, though I think it says exactly what happened. Would you like improve the error message and if so, how?

**Comment by mthalman** [comment]
I would like to not see that error as frequently as I see it. I don't see it in other contexts of fetching package repositories. I'm only seeing it when using the chisel too.

**Comment by mthalman** [comment]
I continue to run into this error periodically. The tool should be more robust to handle communication hiccups, if that's what this is. Is a retry pattern necessary in the logic?

**Comment by mtaron** [comment]
Hitting this pretty regularly in my build pipelines as well. Just had to run it four times to get an image created.

**Comment by rebornplusplus** [comment]
+1. Have been running into this issue quite a lot while building docker images in CI pipelines.

**Comment by rebornplusplus** [comment]
Hiya. Please let me know in this thread if there continue to be occurrences of this issue. https://github.com/canonical/chisel/pull/66 should fix this.

**Comment by norrisjeremy** [comment]
Hmm, ok.
It seemed the issues were intermittent, as sometimes they would succeed, sometimes continue to fail, as we reran failed jobs.
I guess we'll see if the intermittent timeouts persist over time or if they are just a transient issue.
