### ISSUE TITLE
Trigger Snapcarft builds on new releases

### ISSUE THREAD

**Issue by rebornplusplus** [canonical/chisel#146]
The "Build on GitHub" option in Snapcraft triggers on new commits only. Thus [the Snap workflow's Promote job](https://github.com/canonical/chisel/actions/workflows/snap.yml) sits for a long time waiting for the snap with the recent version to be built. But since nothing triggered the build, the workflow will only just keep waiting.

We need to trigger a new build whenever a new release is published.

**Comment by cjdcordeiro** [comment]
This is triggered by the store. If you check the GH action, it's just waiting for a couple of archs, which are still pending store-side.

**Comment by rebornplusplus** [comment]
I manually triggered them actually. The store triggered on the new commit it seems.
