### ISSUE TITLE
chore: update Chisel snap description

### ISSUE THREAD

**Issue by linostar** [canonical/chisel#164]
Update the chisel snap description so it lists the new commands `find` and `info`.

The description in question appears in https://snapcraft.io/chisel and in the output of `snap info chisel`.

**Comment by rebornplusplus** [comment]
Good point, let's see if I can use the `chisel help --all` message as description. That way, there's no need to update the description every few months.

**Comment by rebornplusplus** [comment]
Turns out we cannot do that, yet. :( Raised a ticket for it though: https://github.com/canonical/snapcraft/issues/5123.

Raised #165.
