### ISSUE TITLE
busybox_bins missing requirements

### ISSUE THREAD

**Issue by oaahmad** [canonical/chisel#187]
The `busybox_bins` slice seems to be missing required dependencies. All `busybox` commands fail with a "not found" message. Here is a minimal Dockerfile that reproduces the issue:

```Dockerfile
# docker build -f busybox.Dockerfile .

FROM ubuntu:24.04 AS installer
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
ARG TARGETARCH
ENV PATH=${PATH}:/root/go/bin/
ADD --chown=root --chmod=400 https://go.dev/dl/go1.23.4.linux-${TARGETARCH}.tar.gz /
RUN apt update \
    && apt upgrade \
    && apt install -y --no-install-recommends ca-certificates git \
    && tar xf "go1.23.4.linux-${TARGETARCH}.tar.gz" \
    && chmod -R 500 /go/bin/go \
    && /go/bin/go install "github.com/canonical/chisel/cmd/chisel@v1.0.0" \
    \
    && mkdir /develop-chisel/ \
    && chisel cut "--release=ubuntu-24.04" "--arch=${TARGETARCH}" --root=/develop-chisel/ busybox_bins

FROM scratch AS develop
SHELL ["/usr/bin/busybox", "sh", "-euo", "pipefail", "-c"]
COPY --from=installer --chown=root /develop-chisel/ /
RUN ["/usr/bin/busybox" "--help"]
```

That Dockerfile fails to build at the `RUN ["/usr/bin/busybox" "--help"]` step with a "not found" message. This happens with any `busybox` command (not just `--help`).

The `busybox` binary runs fine when it's inside the `ubuntu:24.04` image, so `ubuntu:24.04` must have some dependency that is not in `/develop-chisel/`.

**Comment by lbussell** [comment]
@oaahmad, if I could chime in:

I think that sometimes on Linux, "not found" can also sometimes mean "failed to launch".

If the `busybox` binaries provided by Ubuntu are built for `Glibc`, and you are trying to run them on Alpine which has `musl` libraries present, then I think the "not found" error really means your binary is failing to link.

Try running `ldd /develop-chisel/usr/bin/busybox`. That will help you debug any linking issues with the executable.

**Comment by cjdcordeiro** [comment]
No worries @oaahmad , mistakes happen :)

I'm glad it's working now. 
As for Alpine, as @lbussell says, the `busybox` binaries that Chisel gives you, will have been built for a Glibc.
