### ISSUE TITLE
[bug] slice definition filenames with "." are not allowed

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel#2]
## How to reproduce

Create a new slice definition filename for the package `libssl1.1` (i.e. `libssl1.1.yaml`). When running `chisel cut`, the following error will be thrown:
 
> error: invalid slice definition filename: "libssl1.1.yaml"")

---
https://github.com/canonical/chisel/blob/4bc0ad75786b54ba084ac4f9aa17032e8aee5043/internal/setup/setup.go#L166

**Comment by niemeyer** [comment]
That's an interesting one. We may need to pick a different character to split the package name and slice name, with underline being the obvious choice.
