### ISSUE TITLE
start versioning Chisel

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel#24]
At the moment, Chisel is not being released nor packaged for distribution. This means users need to build Chisel from source, always pointing to a specific Git commit (typically the head of the `main` branch).

We've had cases already, where the introduction of new Chisel features led to disruptions in the process of building container images which were cloning the `main` branch of Chisel on every build.

For example, older scripts, making use of `git clone https://github.com/canonical/chisel && cd chisel && go build ./cmd/chisel`, stopped working at https://github.com/canonical/chisel/commit/eeba4447c62e328cf69385ad60674892b4d25414, since `go generate internal/deb/version.go` needs to run before the build.

This is normal, and more equally disruptive changes could be expected as Chisel grows.

Instead of forcing Chisel users to pinpoint specific commits, it would be nice to have immutable pointers (tags, releases, or even container images) to specific versions of Chisel.

**Comment by 24367dfa** [comment]
@cjdcordeiro as of 3 weeks ago there is a tagged release of version [v0.8.0](https://github.com/canonical/chisel/releases/tag/v0.8.0)

You might consider closing the Issue ;-)

**Comment by cjdcordeiro** [comment]
Yep. The Chisel snap is now also available: https://snapcraft.io/chisel
