### ISSUE TITLE
NodeJS slice

### ISSUE THREAD

**Issue by jjmartres** [canonical/chisel#65]
Is there a way to add nodejs package sources and create slice for NodejS to be able to create a small docker image for nodeJs application ?

**Comment by karimfromjordan** [comment]
What would a Node.js slice exactly look like? I use Chisel to create [systemd portable services](https://systemd.io/PORTABLE_SERVICES/) and all I really have to do is run `chisel cut --release ubuntu-22.04 --root container libstdc++6_libs` and copy the Node.js executable into the container. For Docker it works the same way.

**Comment by rebornplusplus** [comment]
There is already a PR for Node.js if you want to take a look: https://github.com/canonical/chisel-releases/pull/40

**Comment by cjdcordeiro** [comment]
The PR mentioned by @rebornplusplus has been merged :partying_face: 

There are some examples in the PR that might help you. Feel free to try those new slices and let us know if you encounter any issues.

**Comment by karimfromjordan** [comment]
Just to clarify, slices like this are only possible for packages that are actually in the Ubuntu repository right? So slices for let's say Deno or even Bun wouldn't be possible?

**Comment by yevheniilavrenchuk** [comment]
> Yes, chisel only works with packages from the Ubuntu archives. You can see which archives are supported by looking at the chisel-release `chisel.yaml` file (e.g. https://github.com/canonical/chisel-releases/blob/ubuntu-22.04/chisel.yaml#L3-L7)

Hi, is there a way to use slice configs on ubuntu-22.04, which are written for ubuntu-23.04? 
When I just copied all nodejs dependent config files it didn't work, it is telling that one of the dependencies is missing in archive. 

```
...
16.22 2024/02/02 12:37:14 Fetching ubuntu 22.04 jammy-security suite details...
17.27 2024/02/02 12:37:15 Release date: Fri, 02 Feb 2024 11:25:15 UTC
17.27 2024/02/02 12:37:15 Fetching index for ubuntu 22.04 jammy-security main component...
19.46 2024/02/02 12:37:17 Fetching index for ubuntu 22.04 jammy-security universe component...
21.70 2024/02/02 12:37:20 Fetching ubuntu 22.04 jammy-updates suite details...
22.79 2024/02/02 12:37:21 Release date: Fri, 02 Feb 2024 11:26:07 UTC
22.79 2024/02/02 12:37:21 Fetching index for ubuntu 22.04 jammy-updates main component...
25.50 2024/02/02 12:37:24 Fetching index for ubuntu 22.04 jammy-updates universe component...
27.66 error: slice package "node-undici" missing from archive
```

**Comment by yevheniilavrenchuk** [comment]
> > Hi, is there a way to use slice configs on ubuntu-22.04, which are written for ubuntu-23.04?
> > When I just copied all nodejs dependent config files it didn't work, it is telling that one of the dependencies is missing in archive.
> 
> Hi @yevheniilavrenchuk, I am assuming you copied the slice definition files from the ubuntu-23.04 branch to a ubuntu-22.04 one and running `chisel cut`? That probably won't work because the dependency and package names of 23.04 may not be the same for 22.04. I am afraid the slices would need to be backported for 22.04 first and then you can use from there.

Can you please explain, how that works?
I've made some custom slice configs depending on the libs or bins I need in my chiseled image, but when I'm running `chisel cut --release /my-folder ` it is going to ubuntu-22.04 archive and checking if those files are available there. I don't understand which archive is being checked and how can I add those bins\libs there, so then they could be sliced? 

Thanks in advance!

**Comment by rebornplusplus** [comment]
Will you please paste your `chisel.yaml` file? I think the `archives.ubuntu.version` key is set to `22.04` value. The file should look something like below:

```yaml
...
...
archives:
    ubuntu:
        version: 23.04
        components: [main, universe]
        suites: [lunar, lunar-security, lunar-updates]
...
...
```

**Comment by yevheniilavrenchuk** [comment]
No, it is ubuntu-22.04.
You're right though regarding the packages that are a bit different compared to ubuntu-23.04. I think I understood how to do it in a proper way, so looks like I will add some configs to this repo for 22.04 if all goes fine.

Thanks for now!
