### ISSUE TITLE
Chisel v0.8 fails to install with `go install` command

### ISSUE THREAD

**Issue by lbussell** [canonical/chisel#96]
Hi, I'm trying to install the `chisel` tool in my Docker image with the command recommended by [the official GitHub release](https://github.com/canonical/chisel/releases/tag/v0.8):

```bash
go install github.com/canonical/chisel/cmd/chisel@v0.8
```

The simplest way to reproduce it is to run the following Docker command:
```
$ docker run --entrypoint /bin/sh --rm amd64/golang:1.20 -c "go install github.com/canonical/chisel/cmd/chisel@v0.8"
go: github.com/canonical/chisel/cmd/chisel@v0.8: no matching versions for query "v0.8"
```

It works with `@latest` and `@<commit>`.

**Comment by rebornplusplus** [comment]
Thanks for reporting! Yeah, this will fail. 

> A version query may be one of the following:
> 
> - A fully-specified semantic version, such as v1.2.3, which selects a specific version. See [Versions](https://go.dev/ref/mod#versions) for syntax.
> - **A semantic version prefix, such as v1 or v1.2, which selects the highest available version with that prefix.**
> - A semantic version comparison, such as <v1.2.3 or >=v1.5.6, which selects the nearest available version to the comparison target (the lowest version for > and >=, and the highest version for < and <=).
> - A revision identifier for the underlying source repository, such as a commit hash prefix, revision tag, or branch name. If the revision is tagged with a semantic version, this query selects that version. Otherwise, this query selects a [pseudo-version](https://go.dev/ref/mod#glos-pseudo-version) for the underlying commit. Note that branches and tags with names matched by other version queries cannot be selected this way. **For example, the query v2 selects the latest version starting with v2, not the branch named v2.**
> - The string latest, which selects the highest available release version. If there are no release versions, latest selects the highest pre-release version. If there are no tagged versions, latest selects a pseudo-version for the commit at the tip of the repository’s default branch.
> - ...

-- from [_Version queries, Go Modules Reference_](https://go.dev/ref/mod#version-queries)

---

We will need to create a `v0.8.0` tag. @jnsgruk will you please create the tag?

```
git tag v0.8.0 v0.8
git push origin v0.8.0
```

And in the `v0.8` release notes, I think the following instruction would be more accurate:

> To install **this version** of Chisel, run the following command:
> 
> ```
> go install github.com/canonical/chisel/cmd/chisel@v0.8
> ```

This should fix the issue.

We should maintain [Semantic Versioning 2.0.0](https://semver.org/spec/v2.0.0.html) for our future tags and releases from now on.

**Comment by jnsgruk** [comment]
Yep - I can do that. What I'll probably do is kill the release and "re-release" it with the new tag so we don't end up with too much wierdness. Give me 5.

**Comment by rebornplusplus** [comment]
Yeah, that's better. Please make sure to delete the v0.8 tag in that case.

**Comment by jnsgruk** [comment]
Done... and confirmed this is now fixed:

```
~/code/canonical/chisel  main
❯ go install github.com/canonical/chisel/cmd/chisel@v0.8.0
go: downloading github.com/canonical/chisel v0.8.0
```
